# Jekyll Resume Theme

# Site settings
title: Shantanu Agarwal CV
email: a.shantanu08@gmail.com
description: My CV for Jekyll Resume theme.
baseurl: ""
url: "http://ashantanu.github.io"
name: Shantanu Agarwal
job: Equities Strategist, Goldman Sachs
location: Bangalore, India
languages: C++, Python, Slang
#twitter_username: mattcouchman
github_username:  ashantanu
#codepen_username:  mattcouchman
email_address: a.shantanu08@gmail.com

# Build settings
markdown: ashantanu
