# Jekyll Resume Theme

# Site settings
title: Shantanu
email: a.shantanu08@gmail.com
description: Minimal CV of Shantanu
baseurl: ""
url: "http://ashantanu.github.io"
name: Shantanu
job: Quantitative Strategist
location: Bangalore, India
languages: about AI, Maths and Design 
twitter_username:
github_username:  ashantanu
codepen_username:
email_address: a.shantanu08@gmail.com

# Build settings
markdown: ashantanu

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-D9B0BR8X6K
