# Jekyll Resume Theme

# Site settings
title: Shantanu Agarwal CV
email: a.shantanu08@gmail.com
description: My CV for Jekyll Resume theme.
baseurl: ""
url: "http://ashantanu.github.io"
name: Shantanu
job: Quantitative Strategist
location: Bangalore, India
languages: about AI, Maths and Design 
twitter_username: 0
github_username:  ashantanu
codepen_username: 0 
email_address: a.shantanu08@gmail.com

# Build settings
markdown: ashantanu

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:
